name: BedrockOffhand
version: '${project.version}'
main: me.zombieman.dev.bedrockoffhand.BedrockOffhand
api-version: '1.21'
authors: [mercadanteus, zombieman33]
description: Fork ootimized for compatibility with custom item plugins.
commands:
  offhand:
  offhandadmin:
